### ISSUE TITLE
License for the code

### ISSUE THREAD

**Issue by kumekay** [IvarssonAndreas/mindful-internet-use#27]
Hi @IvarssonAndreas , thank you for the the great project, 

I would like to contribute by making a Firefox port of this extension, however the license of existing code is not specified in the repo. Could you please add a license file or specify it in the project.json?

**Comment by IvarssonAndreas** [comment]
Thank you! Here you go:  [Create LICENSE](https://github.com/IvarssonAndreas/mindful-internet-use/commit/977d3c8a116dea5672d9462336920a04e654322c)
